export ZSH=$HOME/.oh-my-zsh
export DEFAULT_USER=`whoami`

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="powerline"
# settings
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_HIDE_USER_NAME="true"
POWERLINE_RIGHT_A="date"
POWERLINE_NO_BLANK_LINE="true"
POWERLINE_DISABLE_RPROMPT="true"

### POWERLINE-SHELL ###
function powerline_precmd() {
  export PS1="$(~/coding/git-repos/powerline-shell/powerline-shell.py $? --shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}
# uncomment to use powerline-shell
# install_powerline_precmd

#search backwards and forwards with a pattern
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward

# set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward
# fix deleting in insert mode
bindkey -v
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" kill-line
bindkey "^?" backward-delete-char

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew npm osx git vi-mode zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

setopt NO_AUTO_NAME_DIRS
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt NO_HIST_BEEP
setopt SHARE_HISTORY

# colors
export TERM=screen-256color
export TERM="xterm-256color"
# make filetype colors like bash
export LSCOLORS=exfxcxdxbxegedabagacad

# tmux colors
alias tmux="TERM=xterm-256color tmux"

export DOTFILES=$HOME/.dotfiles
# Customize your paths
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=~/bin:$PATH
export PATH=/opt/local/bin:$PATH
export PATH=/usr/local/Cellar/ruby/1.9.3-p327/bin:$PATH
export PATH=/usr/local/Cellar:$PATH
export PATH=/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH

# rbenv stuff
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

export PATH=$PATH:/usr/local/bin/git:$HOME/bin

# POLAR
export POLARPATH=$HOME/coding/polar/projects
export PATH=$PATH:$POLARPATH/MediaEverywhere-CLI/bin

# NPM globals
export PATH=$PATH:/usr/local/share/npm/bin

export PATH=$PATH:$ADBPATH
# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Activate z
. z

# ALIASES
alias ls='ls -FG'
alias ll='ls -a'
alias la='ll -lh'
alias mkdir='mkdir -pv'
alias j='jobs -l'

# npm
alias npmrm='rm -rfv node_modules'
alias npmclr='npm cache clear'
alias npminst='npm install'

# vim
alias viminstall='vim +BundleInstall +qall'
alias vimrestore='vim -S ~/.previous_session.ses'

# work
alias mebuild='me build --watch --debug --serve'
alias melive='me build --watch --debug --serve --live'
alias meclean='me clean'

# misc
alias type='gtypist -b -i'
alias grep='grep --color=auto -C 3'
alias wget='wget -c' # make wget resume downloads by defauls
alias adbforward='adb forward tcp:9222 localabstract:chrome_devtools_remote'
