export ZSH=$HOME/.oh-my-zsh
export DEFAULT_USER=`whoami`

# powerlevel10k (source before oh-my-zsh)
source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme

# disable oh-my-zsh theme since p10k handles the prompt
export ZSH_THEME=""

#search backwards and forwards with a pattern
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward

# set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward
# fix deleting in insert mode
bindkey -v
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" kill-line
bindkey "^?" backward-delete-char

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew npm macos git vi-mode zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

setopt NO_AUTO_NAME_DIRS
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt NO_HIST_BEEP
setopt SHARE_HISTORY

# colors
export TERM=screen-256color
export TERM="xterm-256color"
# make filetype colors like bash
export LSCOLORS=exfxcxdxbxegedabagacad

export DOTFILES=$HOME/.dotfiles
# Customize your paths
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=~/bin:$PATH
export PATH=/opt/local/bin:$PATH
export PATH=/usr/local/Cellar/ruby/1.9.3-p327/bin:$PATH
export PATH=/usr/local/Cellar:$PATH
export PATH=/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH

# PATHS
source $DOTFILES/system/paths

# Activate z
. z

# ALIASES
source $DOTFILES/system/aliases

# Colorized man pages
man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

_has() {
  return $( whence $1 >/dev/null )
}

# FZF {{{1
if [ -e /usr/local/opt/fzf/shell/completion.zsh ]; then
  source /usr/local/opt/fzf/shell/key-bindings.zsh
  source /usr/local/opt/fzf/shell/completion.zsh
fi
if [ -e ~/.fzf ]; then
  _append_to_path ~/.fzf/bin
  source ~/.fzf/shell/key-bindings.zsh
  source ~/.fzf/shell/completion.zsh
fi
if _has fzf; then
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow -g "!.git/*" 2> /dev/null'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_DEFAULT_OPTS='
  --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
  --color info:108,prompt:109,spinner:108,pointer:168,marker:168
  '
fi

source "${DOTFILES}/zsh/functions/common"
