export ZSH=$HOME/.oh-my-zsh
export DEFAULT_USER=`whoami`

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="powerline"
# settings
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_HIDE_USER_NAME="true"
POWERLINE_RIGHT_A="date"
POWERLINE_NO_BLANK_LINE="true"
POWERLINE_DISABLE_RPROMPT="true"

### POWERLINE-SHELL ###
function powerline_precmd() {
  export PS1="$($HOME/powerline-shell.py $? --shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}
# uncomment to use powerline-shell
# install_powerline_precmd

#search backwards and forwards with a pattern
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward

# set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward
# fix deleting in insert mode
bindkey -v
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" kill-line
bindkey "^?" backward-delete-char

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew npm osx git vi-mode zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

setopt NO_AUTO_NAME_DIRS
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt NO_HIST_BEEP
setopt SHARE_HISTORY

# colors
export TERM=screen-256color
export TERM="xterm-256color"
# make filetype colors like bash
export LSCOLORS=exfxcxdxbxegedabagacad

# tmux colors
alias tmux="TERM=xterm-256color tmux"

export DOTFILES=$HOME/.dotfiles
# Customize your paths
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=~/bin:$PATH
export PATH=/opt/local/bin:$PATH
export PATH=/usr/local/Cellar/ruby/1.9.3-p327/bin:$PATH
export PATH=/usr/local/Cellar:$PATH
export PATH=/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH

# PATHS
source $DOTFILES/system/paths

# Activate z
. z

# ALIASES
source $DOTFILES/system/aliases

# Colorized man pages
man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

_has() {
  return $( whence $1 >/dev/null )
}

# FZF {{{1
# FZF is the future. This stuff has to be after some of the Zsh stuff above. Not sure why.
if [ -e /usr/local/opt/fzf/shell/completion.zsh ]; then
  source /usr/local/opt/fzf/shell/key-bindings.zsh
  source /usr/local/opt/fzf/shell/completion.zsh
fi
if [ -e ~/.fzf ]; then
  _append_to_path ~/.fzf/bin
  source ~/.fzf/shell/key-bindings.zsh
  source ~/.fzf/shell/completion.zsh
fi
if _has fzf && _has ag; then
  # export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_DEFAULT_OPTS='
  --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
  --color info:108,prompt:109,spinner:108,pointer:168,marker:168
  '
fi

# set up autoloading and keybindings
fpath=("${DOTFILES}/zsh/functions" "${fpath[@]}")
source "${DOTFILES}/zsh/functions/common"
source "${DOTFILES}/zsh/keybindings.zsh"
