# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/.dotfiles

# source every .sh file in this repo
for file in $DOTFILES/**/*.sh; do
  [ -r "$file" ] && source "$file"
done
unset file

# rbenv stuff
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

# use .localrc for secrets that you do not want in your public, versioned repo
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# add bash-powerline
function _update_ps1()
{
  export PS1="$(~/.powerline-shell.py $?)"
}

# PATHS
export PROMPT_COMMAND="_update_ps1"

export PATH="/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH"

export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

export PATH=$PATH:/usr/local/bin/git:$HOME/bin

# POLAR
export PATH=$PATH:$POLARPATH/MediaEverywhere-CLI/bin

# NPM globals
export PATH=$PATH:/usr/local/share/npm/bin

# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Activate z
. z

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# ALIASES
alias ls='ls -F'
alias ll='ls -aG'
alias la='ll -l'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias mkdir='mkdir -pv'
alias j='jobs -l'

# vim
alias viminstall='vim +BundleInstall +qall'
alias vimrestore='vim -S ~/.previous_session.ses'

# work
alias mebuild='me build --watch --debug --serve'
alias melive='me build --watch --debug --serve --live'
alias meclean='me clean'

# misc
alias grep='grep --color=auto'
alias wget='wget -c' # make wget resume downloads by defauls
alias adbforward='adb forward tcp:9222 localabstract:chrome_devtools_remote'
