# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/.dotfiles

# source every .sh file in this repo
for file in $DOTFILES/**/*.sh; do
  [ -r "$file" ] && source "$file"
done
unset file

# use .localrc for secrets that you do not want in your public, versioned repo
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# add bash-powerline
function _update_ps1()
{
  export PS1="$(~/.powerline-shell.py $?)"
}

export PROMPT_COMMAND="_update_ps1"

# PATHS
source $DOTFILES/system/paths

# Activate z
. z

# set VI mode
set -o vi

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# ALIASES
source $DOTFILES/system/aliases
